### ISSUE TITLE
Vue DevsTool shows duplicated components when using vs-select

### ISSUE THREAD

**Issue by sangdth** [lusaxweb/vuesax#266] opened 2018-09-30 12:45 UTC
When I remove the vs-select, the component list goes back to normal. When I use it, and go to the view that uses vs-select, Vue DevsTool shows duplicated.

Use vs-select:
<img width="516" alt="screen shot 2018-09-30 at 15 37 02" src="https://user-images.githubusercontent.com/1083478/46257762-a0327f00-c4c7-11e8-8de2-040f0b9afdd2.png">

Delete vs-select:
<img width="490" alt="screen shot 2018-09-30 at 15 44 36" src="https://user-images.githubusercontent.com/1083478/46257768-c9eba600-c4c7-11e8-99ff-6ca964b910fa.png">

- Your OS: MacOS X 10.13.6
- Node.js version: 8.11.4
- Vuesax version: 3.4.7
- Browser version: Google Chrome 69.0.3497.100
- Which package manager did you use for the install? Yarn

**Comment by brunokunace** [comment] 2018-10-11 23:53
@sangdth hi!

on print screen, i can see two instances of vuejs, `$vm1` and `$vm2`. You use Event Bus? Why you maintain two instances?

Maybe this, i could not simulate this, all my tests have only one and dont have any code to make duplicate this.

Regards.

**Comment by sangdth** [comment] 2018-10-16 11:31
Hi brunokunace, 
No I do not use event bus. And I do not maintain two instances.

**Comment by Jacrys** [comment] 2018-11-02 13:45
This is a duplicate of #340 it seems.

**Closed** 2018-11-02 17:54 UTC
Labels: bug, help wanted
