### ISSUE TITLE
Sidebar takes two clicks to open when manually closed

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#407] opened 2018-12-14 11:25 UTC
Hey, 
In my app I am using sidebar but with close icon in it. So, when I do `active = false` on click event of button.
Next time when I want to open sidebar it takes two clicks to open sidebar.

heres example,
https://jsfiddle.net/jsinh0001/mxcd1su7/

One more tiny thing is in `vs-chip` component
when we create chip, chip text get some margin on left side which is not centered align when we give padding to `<vs-chip class="p-4">text</vs-chip>`. Which is small fix. :)

**Comment by guastallaigor** [comment] 2018-12-14 14:33
> In my app I am using sidebar but with close icon in it. So, when I do active = false on click event of button.
Next time when I want to open sidebar it takes two clicks to open sidebar.

This can be fixed by putting an `.stop` to the `@click` that opens the sidebar. 
**Example:**

```html
<vs-button @click.stop="active=true" color="primary" type="filled">{{active}}</vs-button>
```

The other one I've created several chips and they were align centered is a way, because the div has padding-right 10px and the text has margin-left 10px, even if it's margin/padding, they still had 10px os the sides so to me it was aligned, so I couldn't reproduce/fix.

**Closed as completed** 2018-12-15 10:23 UTC
