### ISSUE TITLE
Add Ratings component

### ISSUE THREAD

**Issue by AGDholo** [lusaxweb/vuesax#334] opened 2018-10-27 16:42 UTC
For a scoring component, please refer to: https://vuetifyjs.com/zh-Hans/components/ratings

**Comment by Jacrys** [comment] 2018-10-29 16:35
This appears to be a duplicate of #219

**Comment by luisDanielRoviraContreras** [comment] 2018-10-29 19:08
#219

**Closed by luisDanielRoviraContreras** 2018-10-29 19:08 UTC
Labels: New Component, duplicate, enhancement
